# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
