# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0003_auto_20160216_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='full_name',
            field=models.CharField(default='e', max_length=70),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default='k', max_length=30),
        ),
    ]
