# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collective_blog', '0002_postlikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collective_blog.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
