# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_blog', '0004_auto_20160216_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='full_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
